INSERT INTO `lineas_investigacion`(`Nombre`) VALUES
("Lineas de Investigacion 01"),
("Lineas de Investigacion 02"),
("Lineas de Investigacion 03"),
("Lineas de Investigacion 04"),
("Lineas de Investigacion 05"),
("Lineas de Investigacion 06"),
("Lineas de Investigacion 07"),
("Lineas de Investigacion 08"),
("Lineas de Investigacion 09"),
("Lineas de Investigacion 10");